{
    "name": "Student",
    "version": "16.0.1.0.0",
    "summary": """A custom module for schools""",
    "description": """A custom modulo for managin students, books, tuitions and courses""",
    "author": "Uxío Méndez Pazos",
    "maintainer": "Uxío Méndez Pazos",
    "website": "https://github.com/UxioMendezPRO/odoo-school",
    "category": "Tools",
    "depends": [
        "base",
        "sale",
    ],
    "license": "AGPL-3",
    "application": True,
    "data": [
        "security/ir.model.access.csv",
        "views/menu.xml",
        "views/books_course_views.xml",
        "views/course_course_views.xml",
        # "views/student_course_views.xml",
        "views/tuition_course_views.xml",
        "views/res_partner_views.xml",
    ],
    "demo": [],
    "images": ["static/description/banner.png"],
    "installable": True,
    "auto_install": False,
}
