{
    "name": "Student",
    "version": "16.0.1.0.0",
    "summary": """Login User Details & IP Address""",
    "description": """This module records login information of user""",
    "author": "Cybrosys Techno Solutions ",
    "company": "Cybrosys Techno Solutions ",
    "maintainer": "Cybrosys Techno Solutions",
    "website": "https://www.cybrosys.com",
    "category": "Tools",
    "depends": ["base"],
    "license": "AGPL-3",
    "application": True,
    "data": [
        "security/ir.model.access.csv",
        "views/menu.xml",
    ],
    "demo": [],
    "images": ["static/description/banner.png"],
    "installable": True,
    "auto_install": False,
}
