{
    "name": "Student",
    "version": "16.0.1.0.0",
    "summary": """A custom module for schools""",
    "description": """A custom modulo for managin students, books, tuitions and courses""",
    "author": "Uxío Méndez Pazos",
    "maintainer": "Uxío Méndez Pazos",
    "website": "https://github.com/UxioMendezPRO/odoo-school",
    "category": "Tools",
    "depends": ["base"],
    "license": "AGPL-3",
    "application": True,
    "data": [
        "security/ir.model.access.csv",
        "views/menu.xml",
    ],
    "demo": [],
    "images": ["static/description/banner.png"],
    "installable": True,
    "auto_install": False,
}
